site_name: Spello Consulting Smart Device Library
site_url: https://github.com/Spello-Consulting/sc-smart-device

theme:
  name: material
  features:
    - navigation.expand

extra_css:
  - stylesheets/extra.css
    
hooks:
  - scripts/generate_shelly_models.py

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google  # or numpy, sphinx
            show_source: false
            heading_level: 2

nav:
  - Home: index.md
  - Example Config: example_config.md
  - Example Code: 
      - Simple example: code_examples/simple_example.md
      - Basic switch control: code_examples/basic.md
      - Reading energy meters: code_examples/energy_meters.md
      - Reading temperature probes: code_examples/temp_probes.md
      - Using webhooks: code_examples/webhooks.md
      - Using thread safe views: code_examples/device_view.md
      - Using threading: code_examples/device_worker.md  
  - Object Reference: objects.md
  - Shelly Models Library: shelly_models_list.md
  - Shelly Temperature Probes: shelly_temp_probes.md
  - Shelly Webhooks: shelly_webhooks.md
  - API Reference:
      - SCSmartDevice: sc_smart_device.md
      - SmartDeviceView: sc_smart_device_view.md
      - SmartDeviceWorker: sc_smart_device_worker.md

